### ISSUE TITLE
Parallel map

### ISSUE THREAD

**Issue by tpluscode** [zazuko/barnard59-base#10]
As implemented locally in the BLV pipeline, we would want to have built-in support for parallel map step.

This is a small change if through2 is replaced with [parallel-transform](https://npm.im/parallel-transform). It takes additional parameters:

```js
transform(concurrency, { ordered, objectMode } = { ordered: true, objectMode: true }, func) {}
```

I think the proposal is for the step to allow it both ways

```turtle
<#onlyMap> a :Step ;
  code:implementedBy
    [
      code:link <node:barnard59-base#map> ; a code:EcmaScript
    ] ;
  code:arguments (
    [
      code:link <file:../lib/map-callback.js> ; a code:EcmaScript
    ]
  ) .

<#mapWithOptions> a :Step ;
  code:implementedBy
    [
      code:link <node:barnard59-base#map> ; a code:EcmaScript
    ] ;
  code:arguments [
    code:name "map" ;
    code:value [ code:link <file:../lib/map-callback.js> ; a code:EcmaScript ]
  ] , [
    code:name "concurrency" ;
    code:value 100
  ] , [
    code:name "ordered" ;
    code:value false
  ] , [
    code:name "objectMode" ;
    code:value false
  ] .
```

Questions:

1. Do we want to keep the current serial map?
2. What concurrency for positional argument usage? Maybe should be serial by default?

**Comment by bergos** [comment]
The current `map` implementation should be replaced by an implementation that uses `parallel-transform`. The default values should be set in a way that the behavior doesn't change. I think it requires to set the defaults like this:

- `concurrency`: 1
- `ordered`: true
- `objectMode`: true
