### ISSUE TITLE
fetch/fetch.json missing from manifest.ttl

### ISSUE THREAD

**Issue by vhf** [zazuko/barnard59-base#16]
I noticed `fetch.json` doesn't have a definition in `manifest.ttl`

https://github.com/zazuko/barnard59-base/blob/3ab1094584b955e4bde3bc02df9142061ec1e159/lib/fetch.js#L11-L21

**Comment by bergos** [comment]
@vhf on purpose. It will become deprecated in version 1.0. Maybe we make an intermediate 0.x feat version where we remove it already?

**Comment by vhf** [comment]
No need IMO but it's up to you. I was working with some pipeline examples and one of them was using this operation, we'll have to document these deprecation in the changelog otherwise it'll be tough for pipeline users to upgrade.
